# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TickHelp' do
    pod 'VideoSplashKit'
    pod "TextFieldEffects"
    pod 'Firebase', '>= 2.5.1'
    
    source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '8.1'
	pod 'GoogleMaps'

	source 'https://github.com/CocoaPods/Specs.git'
	platform :ios, '7.0'
	pod 'NearbyMessages'
end

target 'TickHelpTests' do

end

target 'TickHelpUITests' do

end

