# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TickHelp' do
	pod 'GeoFire', '>= 1.1'
    pod 'VideoSplashKit'
    pod "TextFieldEffects"
    pod 'Firebase', '>= 2.5.1'
    pod 'JSQMessagesViewController'
end

target 'TickHelpTests' do

end

target 'TickHelpUITests' do

end

