# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TickHelp' do
    pod 'VideoSplashKit'
end

target 'TickHelpTests' do

end

target 'TickHelpUITests' do

end

